name: Build and release plugin

on:
    push:
        tags:
            - "*"

env:
    PLUGIN_NAME: obsidian-note-type

permissions:
    contents: write
    id-token: write
    attestations: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  run_install: false

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: ".node-version"
                  cache: "pnpm"

            - name: Build
              run: |
                  pnpm install
                  pnpm run build

            - name: Generate artifact attestations
              uses: actions/attest-build-provenance@v2
              with:
                  subject-path: |
                      main.js
                      styles.css

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  name: ${{ github.ref_name }}
                  generate_release_notes: true
                  files: |
                      main.js
                      manifest.json
                      styles.css
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
